update project

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -29,6 +29,9 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: linkopus/invoiceplane:latest
+          build-args: |
+            NGINX_CERTIFICATE=${{ secrets.NGINX_CERTIFICATE }}
+            NGINX_PRIVATE_KEY=${{ secrets.NGINX_PRIVATE_KEY }}
 
       - name: Deploy to Dev Environment
         uses: appleboy/ssh-action@master
@@ -39,20 +42,28 @@ jobs:
           script: |
             echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
             docker pull linkopus/invoiceplane:latest
-            if [ "$(docker ps -aq -f name=invoiceplane-app)" ]; then
-              docker stop invoiceplane-app
-              docker rm invoiceplane-app
-            fi
-            docker run -d --name invoiceplane-app \
+            docker stop invoiceplane || true
+            docker rm invoiceplane || true
+            docker run -d --name invoiceplane \
               -p ${{ secrets.NGINX_HTTPS_PORT }}:${{ secrets.NGINX_HTTPS_PORT }} \
               -p ${{ secrets.NGINX_HTTP_PORT }}:${{ secrets.NGINX_HTTP_PORT }} \
               -v /home/mohammed/InvoicePlane:/var/www/html \
               linkopus/invoiceplane:latest
             docker logout
-            # Exécuter le script de mise à jour du projet
-            cd /home/mohammed/InvoicePlane
-            git reset --hard
-            git clean -fd
-            git fetch origin
-            git checkout development
-            git pull origin development
+            # Vérifier que le répertoire existe
+            if [ -d "/home/mohammed/InvoicePlane" ]; then
+              cd /home/mohammed/InvoicePlane
+              if [ -d ".git" ]; then
+                git reset --hard
+                git clean -fd
+                git fetch origin
+                git checkout development
+                git pull origin development
+              else
+                echo "Error: /home/mohammed/InvoicePlane is not a git repository."
+                exit 1
+              fi
+            else
+              echo "Error: /home/mohammed/InvoicePlane does not exist."
+              exit 1
+            fi
